[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  ".git",
  "secrets/home/crypted/*",
  "modules/user/gui/kitty/conf/tab_bar.py",
]

[tool.black]
line-length = 100
target-version = ['py310']
exclude = '''
/(\
  \.git\
 | secrets/home/crypted\
 | modules/user/gui/kitty/conf/tab_bar.py\
)/
'''
